apps/crm_web/lib/crm_web/router.ex
defmodule CrmWeb.Router do
  use CrmWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CrmWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/contacts", ContactController, only: [:index, :show, :new, :create, :delete]
    resources "/updates", UpdateController, only: [:new, :create]
    resources "/groups", GroupController, only: [:index, :new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", CrmWeb do
  #   pipe_through :api
  # end
end

apps/crm_web/lib/crm_web/controllers/contact_controller.ex
defmodule CrmWeb.ContactController do
  use CrmWeb, :controller

  def index(conn, _params) do
    contacts = Crm.list_contacts()
    render(conn, "index.html", contacts: contacts)
  end

  def show(conn, %{"id" => id}) do
    contact = Crm.get_contact_with_preloads(id)
    render(conn, "show.html", contact: contact)
  end

  def new(conn, _params) do
    contact = Crm.new_contact()
    groups = Crm.list_groups()
    render(conn, "new.html", contact: contact, groups: groups)
  end

  def create(conn, %{"contact" => contact_params}) do
    case Crm.insert_contact(contact_params) do
      {:ok, contact} -> redirect(conn, to: Routes.contact_path(conn, :show, contact))
      {:error, contact} -> render(conn, "new.html", contact: contact, groups: Crm.list_groups())
    end
  end

  def delete(conn, %{"id" => id}) do
    contact = Crm.get_contact(id)
    Crm.delete_contact(contact)
    redirect(conn, to: Routes.contact_path(conn, :index))
  end
end

apps/crm_web/lib/crm_web/controllers/group_controller.ex
defmodule CrmWeb.GroupController do
  use CrmWeb, :controller

  def new(conn, _params) do
    group = Crm.new_group()
    render(conn, "new.html", group: group)
  end

  def create(conn, %{"group" => group}) do
    case Crm.insert_group(group) do
      {:ok, _group} ->
        conn
        |> put_flash(:info, "Group correctly created")
        |> redirect(to: Routes.group_path(conn, :index))

      {:error, group} ->
        render(conn, "new.html", group: group)
    end
  end

  def index(conn, _params) do
    groups = Crm.list_groups()
    render(conn, "index.html", groups: groups)
  end
end

apps/crm_web/lib/crm_web/controllers/page_controller.ex
defmodule CrmWeb.PageController do
  use CrmWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/crm_web/lib/crm_web/controllers/update_controller.ex
defmodule CrmWeb.UpdateController do
  use CrmWeb, :controller

  def new(conn, _params) do
    update = Crm.new_update()
    contacts = Crm.list_contacts()
    render(conn, "new.html", update: update, contacts: contacts)
  end

  def create(conn, %{"update" => update_params}) do
    case Crm.insert_update(update_params) do
      {:ok, _update} ->
        conn
        |> put_flash(:info, "Update correctly added")
        |> redirect(to: Routes.contact_path(conn, :index))

      {:error, update} ->
        render(conn, "new.html", update: update, contacts: Crm.list_contacts())
    end
  end
end

apps/crm_web/lib/crm_web/views/contact_view.ex
defmodule CrmWeb.ContactView do
  use CrmWeb, :view
end

apps/crm_web/lib/crm_web/views/error_view.ex
defmodule CrmWeb.ErrorView do
  use CrmWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/crm_web/lib/crm_web/views/group_view.ex
defmodule CrmWeb.GroupView do
  use CrmWeb, :view
end

apps/crm_web/lib/crm_web/views/layout_view.ex
defmodule CrmWeb.LayoutView do
  use CrmWeb, :view
end

apps/crm_web/lib/crm_web/views/page_view.ex
defmodule CrmWeb.PageView do
  use CrmWeb, :view
end

apps/crm_web/lib/crm_web/views/update_view.ex
defmodule CrmWeb.UpdateView do
  use CrmWeb, :view
end

apps/crm_web/lib/crm_web/templates/contact/index.html.eex
<ul>
    <%= for contact <- @contacts do %>
        <li><%= link(CrmWeb.GlobalHelpers.get_full_name(contact), to: Routes.contact_path(@conn, :show, contact)) %> - <%= button("delete", to: Routes.contact_path(@conn, :delete, contact), method: :delete) %></li>
    <% end %>
</ul>

apps/crm_web/lib/crm_web/templates/contact/new.html.eex
<h1>New Contact</h1>

<%= form_for @contact, Routes.contact_path(@conn, :create), fn f -> %>
    <%= if @contact.action do %>
        <div class="alert alert-danger">
        Unfortunately, there are errors in your
        submission. Please correct them below.
        </div>
    <% end %>

    <%= label f, :first_name %>
    <%= text_input f, :first_name %>
    <%= error_tag f, :first_name %>

    <%= label f, :last_name %>
    <%= text_input f, :last_name %>
    <%= error_tag f, :last_name %>

    <%= label f, :days_for_contact %>
    <%= number_input f, :days_for_contact %>
    <%= error_tag f, :days_for_contact %>

    <%= label f, :group %>
    <%= select f, :group, Enum.map(@groups, fn group -> {group.name, group.id} end) %>
    <%= error_tag f, :group %>

    <div>
        <%= submit "Submit" %>
    </div>
<% end %>

apps/crm_web/lib/crm_web/templates/contact/show.html.eex
<h1><%= CrmWeb.GlobalHelpers.get_full_name(@contact) %></h1>
<%= if @contact.days_for_contact do %>
    <p>Days before contact : <%= @contact.days_for_contact %></p>
<% end %>
<h2>Updates</h2>
<%= for update <- @contact.updates do %>
    <p><%= update.activity %></p>
<% end %>
<h2>Notes</h2>
<%= for note <- @contact.notes do %>
    <p><%= note %></p>
<% end %>
<%= link("+ Add an update", to: Routes.update_path(@conn, :new)) %>

apps/crm_web/lib/crm_web/templates/group/index.html.eex
<ul>
    <%= for group <- @groups do %>
        <li><%= group.name %></li>
    <% end %>
</ul>

apps/crm_web/lib/crm_web/templates/group/new.html.eex
<h1>New Group</h1>

<%= form_for @group, Routes.group_path(@conn, :create), fn f -> %>
    <%= if @group.action do %>
        <div class="alert alert-danger">
        Unfortunately, there are errors in your
        submission. Please correct them below.
        </div>
    <% end %>

    <%= label f, :name %>
    <%= text_input f, :name %>
    <%= error_tag f, :name %>

    <div>
        <%= submit "Submit" %>
    </div>
<% end %>

apps/crm_web/lib/crm_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CrmWeb · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/crm_web/lib/crm_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed or maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>

apps/crm_web/lib/crm_web/templates/update/new.html.eex
<h1>Create a new update</h1>

<%= form_for @update, Routes.update_path(@conn, :create), fn f -> %>
    <%= if @update.action do %>
        <div class="alert alert-danger">
        Unfortunately, there are errors in your
        submission. Please correct them below.
        </div>
    <% end %>

    <%= label f, :contacts %>
    <%= multiple_select f, :contacts, Enum.map(@contacts, fn contact -> {CrmWeb.GlobalHelpers.get_full_name(contact), contact.id} end) %>
    <%= error_tag f, :contacts %>

    <%= label f, :activity %>
    <%= text_input f, :activity %>
    <%= error_tag f, :activity %>

    <%= label f, :start %>
    <%= date_select f, :start %>
    <%= error_tag f, :start %>

    <%= label f, :end %>
    <%= date_select f, :end %>
    <%= error_tag f, :end %>

    <%= label f, :note %>
    <%= textarea f, :note %>
    <%= error_tag f, :note %>

    <div>
        <%= submit "Submit" %>
    </div>
<% end %>